### ISSUE TITLE
Importing issues with screenshots

### ISSUE THREAD

**Issue by nagey** [linearapp/linear-import#20]
Any time that the importer encounters an image URL in an issue, it fails like this:

```
Error occurred while importing:

{
  "errors": [
    {
      "message": "Unsupported file type 5154001a-16c8-474d-b27f-38208b8ad687",
      "path": [
        "imageUploadFromUrl"
      ],
      "locations": [
        {
          "line": 2,
          "column": 7
        }
      ],
      "extensions": {
        "type": "invalid input",
        "userError": true
      }
    }
  ],
  "data": null
}
Failed to replace image Unsupported file type 5154001a-16c8-474d-b27f-38208b8ad687: {"response":{"errors":[{"message":"Unsupported file type 5154001a-16c8-474d-b27f-38208b8ad687","path":["imageUploadFromUrl"],"locations":[{"line":2,"column":7}],"extensions":{"type":"invalid input","userError":true}}],"data":null,"status":200},"request":{"query":"mutation uploadImage($url: String!) {\n      imageUploadFromUrl(url: $url) {\n        success\n        url\n      }\n    }\n  ","variables":{"url":"https://images.zenhubusercontent.com/URL-REDACTED"}}}
```

is there a way to have linear take these urls and incorporate them in the description or anything like that? Also, is there any way to know which issues succeeded or failed?

**Comment by nagey** [comment]
Sorry, to be more exact, issue seems to be that the importer is trying to guess a mime type from a URL (which these don't have — `https://images.zenhubusercontent.com/5e4f3958eb3738f065b5834f/85f561ba-29e6-46e9-8f03-0453b457664a` is an exmaple.

Would it be possible to grab the mime type from the URL itself and make the decision that way?

**Comment by jorilallo** [comment]
Sorry about that. I'll make the change to determine the type from the headers instead. I already have a PR open so expect this to work early next week

**Comment by jorilallo** [comment]
@nagey Wanted to let you know this has finally landed in our API. Sorry for the delay
