### ISSUE TITLE
Github import - convert tasks

### ISSUE THREAD

**Issue by rdewolff** [linearapp/linear-import#25]
Would be great to add proper task conversion from github.

Currently, github tasks are written as: 
```
- [ ] taskname
- [ ] another task
```

In Linear, task are noted as:
```
[ ] taskname
[ ] another task
```

The import script should properly convert this.

Currently, a task imported from github looks like a HTML list element with [ ] appended to it.

**Comment by aydenp** [comment]
I believe this is soon to be fixed on the API side. Worth closing when that's deployed (cc: @jorilallo @rlargman).

**Comment by rlargman** [comment]
This is fixed!
