### ISSUE TITLE
Error occurred while importing

### ISSUE THREAD

**Issue by alxckn** [linearapp/linear-import#51]
I tried to launch an import task using this CLI to upload to Linear github issues.

It failed with the following message:

```
Error occurred while importing:

{
  "errors": [
    {
      "message": "invalid issue description",
      "path": [
        "issueCreate"
      ],
      "locations": [
        {
          "line": 12,
          "column": 13
        }
      ],
      "extensions": {
        "type": "invalid input",
        "userError": true,
        "userPresentableMessage": {}
      }
    }
  ],
  "data": null
}
```

I retried a second time and it failed exactly on the same issue. Unfortunately I cannot paste here the issue description that caused this error.

**Comment by alxckn** [comment]
I've narrowed down the specific content in the issue description that seem to trigger the error:

```graphql
mutation {
  issueCreate(
    input: {
      title: "This does not work"
      description: "- <whatever>:\r\n![image](https://i.imgur.com/eK1Xi1j.jpg)"
      teamId: "<teamid>"
    }
  ) {
    success
    issue {
      id
    }
  }
}
```

This will systematically result in an error:

```json
{
  "errors": [
    {
      "message": "invalid issue description",
      "path": [
        "issueCreate"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {
        "type": "invalid input",
        "userError": true,
        "userPresentableMessage": {}
      }
    }
  ],
  "data": null
}
```

There are also weird behaviors associated to the presence of the image it seems. Sometimes, the image will be loaded, sometimes it won't. The text content can also not be present.

`description: "![image](https://i.imgur.com/eK1Xi1j.jpg)"` (`success: true`)
![image](https://user-images.githubusercontent.com/11556013/103760313-36de3680-5015-11eb-992a-b984c3c17c8e.png)

`description: "- <whatever>: ![image](https://i.imgur.com/eK1Xi1j.jpg)"` (`success: true`):
![image](https://user-images.githubusercontent.com/11556013/103760241-1c0bc200-5015-11eb-81c0-6baeee90effa.png)

`description: "- whatever:"` (`success: true`):
![image](https://user-images.githubusercontent.com/11556013/103760421-5ffec700-5015-11eb-8aa4-624eb2e8beb4.png)

**Comment by rlargman** [comment]
This was an API side problem rather than an importer issue. I've merged a fix, and that should be live soon (~15-20 minutes). Let me know if you still see problems!

**Comment by alxckn** [comment]
@rlargman Thanks for taking a look. Indeed an API problem, please let me know if there'd have been a better place to post the issue.

For the issue itself, I was able to redo the test and indeed the server will issue a success response for all of these cases.

However the result within the Linear app is still a bit surprising, here are 2 examples:

`description: "- whatever: ![image](https://i.imgur.com/eK1Xi1j.jpg)"` results in:
![image](https://user-images.githubusercontent.com/11556013/105326200-c7984300-5bcd-11eb-80fb-1f0c3051a65a.png)
(no image)

`description: "- whatever:\n![image](https://i.imgur.com/eK1Xi1j.jpg)"`
![image](https://user-images.githubusercontent.com/11556013/105326298-df6fc700-5bcd-11eb-825a-396a9c17d83a.png)
(image not imported and replaced with a placeholder saying 'image')

**Comment by rlargman** [comment]
@alxckn For Linear app issues, you can report bugs or request features through the app itself, under `Help & Feedback` at the bottom of the sidebar, or [by joining our Slack group](https://join.slack.com/t/linearcustomers/shared_invite/enQtNzMwNjU5NTkxMjMyLWY1OWNhMTk0ODdjMzEwNmYyODNlMmRjZjllMzk3ZDFlZjlhYmIzNDAzMjJlMjZhMDkwNjI2ODU5MjAzMWIwNjk).

Currently, you can only add images to issues via markdown through the API. To add them in the app you must upload them through drag & drop, or by selecting or pasting them. But, it's a good suggestion to be able to add images through markdown as well!

**Comment by alxckn** [comment]
@rlargman thanks!

> Currently, you can only add images to issues via markdown through the API

Just to clarify, I do think there is still a bug with this very feature, i.e. depending on the __markdown__ content formatting uploaded __via the API__, some words or images will be __discarded__. As a result the content copied over from github might be missing things.

Also, I did retry a full import from github using linear-import but it failed again with the same kind of error, this time on another github issue (`invalid issue description`).

**Comment by rlargman** [comment]
@alxckn In your comment above, if I make a request with the description you provided like so:
```
mutation {
  issueCreate(
    input: {
      title: "New Issue Title 2",
      teamId: "xxx-my-team-id",
      description: "- whatever:\n![image](https://i.imgur.com/eK1Xi1j.jpg)",
    }
  ) {
    success
    issue {
      id
      title
      state {
        id
        name
      }
    }
  }
}
```
It works as expected: 
<img width="400" alt="Screen Shot 2021-01-21 at 11 19 11 AM" src="https://user-images.githubusercontent.com/4577711/105401011-7f335200-5bda-11eb-8368-9072e05c3ca8.png">

What is the query you are doing with that description?

For the other description you provided: `description: "- whatever: ![image](https://i.imgur.com/eK1Xi1j.jpg)"`, an image cannot be an item in a bulleted list, so that behavior is as expected. 

Do you have examples of the other github issues where the issue description was invalid in the import? There could still be some other edge cases we haven't accounted for with images in descriptions that I need to fix.

**Comment by alxckn** [comment]
@rlargman 

I just did the following query:

```graphql
mutation {
  issueCreate(
    input: {
      title: "Text followed by a line break and an image"
      description: "- some text:\n![image](https://i.imgur.com/uDIxI5P.jpg)"
      teamId: "xxxx"
    }
  ) {
    success
    issue {
      id
      title
    }
  }
}
```

and end up with this:
![image](https://user-images.githubusercontent.com/11556013/105409884-6609c000-5c31-11eb-94ac-7669e07986d4.png)

> an image cannot be an item in a bulleted list, so that behavior is as expected

Good to know. To be honest I don't even know whether we have such a case within our issues, I was just trying to find relevant test cases. One thing to note is that putting `- whatever: ![image](https://i.imgur.com/eK1Xi1j.jpg)` in a github issue description or comment will work (as in it will then display a bullet point followed by an image below).

I stripped the issue description+comments that were blocking the last import and got to this issue mutation query with a seemingly pretty harmless description:

```graphql
mutation {
  issueCreate(
    input: {
      title: "A new breaking issue"
      description: "---**@bobo** 2019-04-11\n\n![image](https://i.imgur.com/uDIxI5P.jpg)"
      teamId: "xxx-team-id"
    }
  ) {
    success
    issue {
      id
      title
    }
  }
}
```

Which results in:

```graphql
{
  "errors": [
    {
      "message": "invalid issue description",
      "path": [
        "issueCreate"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {
        "type": "invalid input",
        "userError": true,
        "userPresentableMessage": {}
      }
    }
  ],
  "data": null
}
```

**Comment by rlargman** [comment]
@alxckn The issue with image uploads not working properly should be fixed now. I've tried with both of the issue descriptions you have above, and both are working for me now. How does it look on your end?

**Comment by alxckn** [comment]
@rlargman I was able to complete a full import today, thanks!
